import * as feature from "./feature";
import { Session } from "./session";

const session = new Session();
session.connection.onInitialize(feature.initialize(session));
session.connection.onDocumentHighlight(feature.documentHighlight(session));
session.connection.onCodeLens(feature.codeLens(session));
session.connection.onCodeLensResolve(feature.codeLensResolve(session));
session.connection.onCompletion(feature.completion(session));
session.connection.onCompletionResolve(feature.completionResolve(session));
session.connection.onDefinition(feature.definition(session));
session.connection.onDocumentFormatting(feature.documentFormatting(session));
session.connection.onDocumentOnTypeFormatting(feature.documentOnTypeFormatting(session));
session.connection.onDocumentRangeFormatting(feature.documentRangeFormatting(session));
session.connection.onDocumentSymbol(feature.documentSymbol(session));
session.connection.onHover(feature.hover(session));
session.connection.onReferences(feature.references(session));
session.connection.onRenameRequest(feature.rename(session));
session.connection.onRequest({ method: "caseAnalysis" }, feature.caseAnalysis(session));
session.listen();
